import '../styles/globals.css'
import { Footer } from './components/Footer'
import { Navigation } from "./components/Navigation"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>ROCKET LAUNCHER</title>
      </head>
      <body className='bg-[#fffffc]'>
        <Navigation/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
